const API_URL = {
  activeFeaturesGrouped: `/api/active-features-grouped`,
  addAttribute: `/api/add-attribute`,
  addAttributeValue: `/api/add-attribute-value`,
  addChat: `/api/add-chat`,
  addContactUs: `/api/add-contact-us`,
  addDepartment: `/api/add-department`,
  addDesignation: `/api/add-designation`,
  addLeave: `/api/add-leave`,
  addMeeting: `/api/add-meeting`,
  addNotification: `/api/add-notification`,
  addOpportunity: `/api/add-opportunity`,
  addPriority: `/api/add-priority`,
  addProject: `/api/add-project`,
  addProjectPhase: `/api/add-project-phase`,
  addProspectContactPerson: `/api/add-prospect-contact-person`,
  addProspectLogActivity: `/api/add-prospect-log-activity`,
  addProspectStage: `/api/add-prospect-stage`,
  addQuotation: `/api/add-quotation`,
  addRole: `/api/add-role`,
  addTask: `/api/add-task`,
  addTaskFollowup: `/api/add-task-followup`,
  addTaskStatus: `/api/add-task-status`,
  addTaskType: `/api/add-task-type`,
  addUserActivity: `/api/add-user-activity`,
  approveLeaveById: (id) => `/api/approve-leave/${id}`,
  approveTimeAdjustment: `/api/approve-time-adjustment`,
  assignTask: `/api/assign-task`,
  attendanceReportDashboard: `/api/attendance-report-dashboard`,
  attendanceReportByUserCountData: `/api/attendanceReportByUser-count-data`,
  calculateEffortProspect: `/api/calculate-effort-prospect`,
  cartMultiple: `/api/cart/multiple`,
  cartOrderByOrderId: (orderId) => `/api/cart/order/${orderId}`,
  changeOrderStatus: `/api/change-order-status`,
  changePassword: `/api/change-password`,
  changeProspectStage: `/api/change-prospect-stage`,
  changeRoleByUserId: (userId) => `/api/change-role/${userId}`,
  changeDepartmentByUserId: (userId) => `/api/change-department/${userId}`,
  changeDesignationByUserId: (userId) => `/api/change-designation/${userId}`,
  checkInNow: `/api/check-in-now`,
  checkOutNow: `/api/check-out-now`,
  checkProspectnameAvaiblity: `/api/check-prospectname-avaiblity`,
  clients: `/api/clients`,
  conversationRoom: `/api/conversation-room`,
  conversationRoomAdd: `/api/conversation-room/add`,
  convertToProspect: `/api/convert-to-prospect`,
  createPost: `/api/create-post`,
  createProspect: `/api/create-prospect`,
  createMainCategory: `/api/createMainCategory`,
  createProduct: `/api/createProduct`,
  deleteDepartmentById: (id) => `/api/delete-department/${id}`,
  deleteDesignationById: (id) => `/api/delete-designation/${id}`,
  deleteFollowupById: (id) => `/api/delete-followup/${id}`,
  deleteNotice: `/api/delete-notice`,
  deletePriorityById: (id) => `/api/delete-priority/${id}`,
  deleteProdductImageById: (id) => `/api/delete-prodduct-image/${id}`,
  deleteProductById: (id) => `/api/delete-product/${id}`,
  deleteProspectById: (id) => `/api/delete-prospect/${id}`,
  deleteRoleById: (id) => `/api/delete-role/${id}`,
  deleteTaskImageById: (id) => `/api/delete-task-image/${id}`,
  deleteTaskStatusById: (id) => `/api/delete-task-status/${id}`,
  deleteTaskTypeById: (id) => `/api/delete-task-type/${id}`,
  deleteVideoLinkById: (id) => `/api/delete-video-link/${id}`,
  detailsOpportunityById: (id) => `/api/details-opportunity/${id}`,
  getActiveCategories: `/api/get-active-categories`,
  getAllEmployee: `/api/get-all-employee`,
  getAllLeave: `/api/get-all-leave`,
  getAllProspect: `/api/get-all-prospect`,
  getAllTask: `/api/get-all-task`,
  getAllTaskByStatus: `/api/get-all-task-by-status`,
  getAllTaskDepartmentById: (id) => `/api/get-all-task-department/${id}`,
  getAllUserActivity: `/api/get-all-user-activity`,
  getAllWithdraw: `/api/get-all-withdraw`,
  getAssignedTaskById: (id) => `/api/get-assigned-task/${id}`,
  getAttendanceAdjustment: `/api/get-attendance-adjustment`,
  getAttendanceDate: (date) => `/api/get-attendance-date?date=${date}`,
  getAttendanceReportUser: `/api/get-attendance-report-user`,
  getAttribute: `/api/get-attribute`,
  getAttributeValueById: (id) => `/api/get-attribute-value/${id}`,
  getBalanceAddDataUserById: (id) => `/api/get-balance-add-data-user/${id}`,
  getBrands: `/api/get-brands`,
  getButtonVisit: `/api/get-button-visit`,
  getChatByConversationid: `/api/get-chat-by-conversationid`,
  getChatByProjectId: `/api/get-chat-by-projectId`,
  getClientDetailsById: (id) => `/api/get-client-details/${id}`,
  getContactPersonProspectById: (id) => `/api/get-contact-person-prospect/${id}`,
  getContactUs: `/api/get-contact-us`,
  getDashboardReport: `/api/get-dashboard-report`,
  getDepartment: `/api/get-department`,
  getDepartmentWithUser: `/api/get-department-with-user`,
  getDesignation: `/api/get-designation`,
  getDistrictByDivisionId: (divisionId) => `/api/get-district?division_id=${encodeURIComponent(divisionId)}`,
  getDivision: `/api/get-division`,
  getEmpLeaveReportById: (id) => `/api/get-emp-leave-report/${id}`,
  getEmpLeaveById: (id) => `/api/get-emp-leave/${id}`,
  getFacebookLeads: `/api/get-facebook-leads`,
  getIndustryType: `/api/get-industry-type`,
  getInformationSource: `/api/get-information-source`,
  getLeaveType: `/api/get-leave-type`,
  getLogActivityByProspectById: (id) => `/api/get-log-activity-by-prospect/${id}`,
  getMeetingByProspectById: (id) => `/api/get-meeting-by-prospect/${id}`,
  getNotificationsById: (id) => `/api/get-notifications/${id}`,
  getOpportunitiesByStage: `/api/get-opportunities-by-stage`,
  getOrderDetailsById: (id) => `/api/get-order-details/${id}`,
  getPriorities: `/api/get-priorites`,
  getProfile: (id) => `/api/get-profile?user_id=${id}`,
  getProject: `/api/get-project`,
  getProjectByDepartmentById: (id) => `/api/get-project-by-department/${id}`,
  getProjectDetailsById: (id) => `/api/get-project-details/${id}`,
  getProjectPhaseById: (id) => `/api/get-project-phase/${id}`,
  getProspectByStage: `/api/get-prospect-by-stage`,
  getProspectDetailById: (id) => `/api/get-prospect-detail/${id}`,
  getProspectMonthReport: `/api/get-prospect-month-report`,
  getProspectSourceWise: `/api/get-prospect-source-wise`,
  getProspectStageOverview: `/api/get-prospect-stage-overview`,
  getProspectStages: `/api/get-prospect-stages`,
  getProspectViewPreference: (userId) => `/api/get-prospect-view-preference?user_id=${encodeURIComponent(userId)}`,
  getProspectWeeklyReport: `/api/get-prospect-weekly-report`,
  prospectBulkTemplate: `/api/prospect-bulk-import/template`,
  prospectBulkPreview: `/api/prospect-bulk-import/preview`,
  prospectBulkConfirm: `/api/prospect-bulk-import/confirm`,
  prospectBulkHistory: `/api/prospect-bulk-import/history`,
  prospectBulkDetails: `/api/prospect-bulk-import/`,
  getRole: `/api/get-role`,
  getTaskActivitiesByTaskIdById: (id) => `/api/get-task-activitiesByTaskId/${id}`,
  getTaskFollowupsByTaskIdById: (id) => `/api/get-task-followupsByTaskId/${id}`,
  getTaskReportById: (id) => `/api/get-task-report/${id}`,
  getTaskStatus: `/api/get-task-status`,
  getTaskStatusByDepartmentById: (departmentId) => `/api/get-task-status-by-department/${departmentId}`,
  getTaskType: `/api/get-task-type`,
  getTaskTypeByDepartmentById: (departmentId) => `/api/get-task-type-by-department/${departmentId}`,
  getUpozelaByDistrictId: (districtId) => `/api/get-upozela?district_id=${encodeURIComponent(districtId)}`,
  getUserActivity: (id) => `/api/get-user-activity?user_id=${id}`,
  getUserModePreference: (userId) => `/api/get-user-mode-preference?user_id=${encodeURIComponent(userId)}`,
  getUserTaskById: (id) => `/api/get-user-task/${id}`,
  getUserWaitingTaskById: (id) => `/api/get-user-waiting-task/${id}`,
  getWarehouse: `/api/get-warehouse`,
  getWarehouses: `/api/get-warehouses`,
  getWithdrawUserById: (id) => `/api/get-withdraw-user/${id}`,
  getAllOrders: `/api/getAllOrders`,
  getAllposts: `/api/getAllposts`,
  getBrands2: `/api/getBrands`,
  getProductCategories: `/api/getProductCategories`,
  getProductDetailsById: (id) => `/api/getProductDetails/${id}/0`,
  getProductImagesByProductIdById: (id) => `/api/getProductImagesByProductId/${id}`,
  getProfile2: (id) => `/api/getProfile?id=${id}`,
  influencingRoles: `/api/influencing-roles`,
  isCheckedinToday: (userId) => `/api/is-checkedin-today?user_id=${userId}`,
  login: `/api/login`,
  logout: (id) => `/api/logout?user_id=${id}`,
  markPaidById: (id) => `/api/mark-paid/${id}`,
  modulePermissionByCompanyID: (companyID) => `/api/module/permission/${companyID}`,
  noticeAdd: `/api/notice/add`,
  noticeAll: `/api/notice/all`,
  productOrdersAddOrder: `/api/product-orders/add-order`,
  productOrdersGetOrder: `/api/product-orders/get-order`,
  productVariantAdd: `/api/product-variant/add`,
  productVariantAllById: (id) => `/api/product-variant/all/${id}`,
  productVariantGetAllVarients: `/api/product-variant/get-all-varients`,
  productActive: `/api/product/active`,
  productAdd: `/api/product/add`,
  productUpdateById: (id) => `/api/product/update/${id}`,
  productDeleteById: (id) => `/api/product/delete/${id}`,
  projectMembersTaskCountById: (id) => `/api/project-members-task-count/${id}`,
  projectMembersById: (id) => `/api/project-members/${id}`,
  projectMembersAddMultiple: `/api/project-members/add-multiple`,
  projectWorkshopAddWorkShop: `/api/project-workshop/add-work-shop`,
  projectWorkshopAll: `/api/project-workshop/all`,
  projectWorkshopGetByProjectById: (id) => `/api/project-workshop/get-by-project/${id}`,
  projectWorkshopRemoveById: (id) => `/api/project-workshop/remove/${id}`,
  projectsFeaturesById: (id) => `/api/projects/features/${id}`,
  prospectConcernPersonById: (id) => `/api/prospect-concern-person/${id}`,
  prospectConcernPersonAdd: `/api/prospect-concern-person/add`,
  prospectConcernPersonRemove: `/api/prospect-concern-person/remove`,
  prospectstageByLogAndProspect: `/api/prospectstage-by-log-and-prospect`,
  quotationsProspectById: (id) => `/api/quotations/prospect/${id}`,
  registerEmployee: `/api/register-employee`,
  rejectLeaveById: (id) => `/api/reject-leave/${id}`,
  reportText: `/api/report-text`,
  requestAttendanceAdjustment: `/api/request-attendance-adjustment`,
  roleFeaturePermissionsByRoleId: (roleId) => `/api/role-feature-permissions/${roleId}`,
  stockList: `/api/stock/list`,
  taskByProjectPhaseById: (id) => `/api/task-by-project-phase/${id}`,
  taskByProjectById: (id) => `/api/task-by-project/${id}`,
  taskDetailsById: (id) => `/api/task-details/${id}`,
  taskImagesById: (id) => `/api/task/images/${id}`,
  taskImagesAdd: `/api/task/images/add`,
  ticketsAddTicket: `/api/tickets/add-ticket`,
  ticketsAll: `/api/tickets/get-all-ticket`,
  ticketsChangeStatusById: (id) => `/api/tickets/change-status/${id}`,
  ticketsConvertToTaskById: (id) => `/api/tickets/convert-to-task/${id}`,
  ticketsDeleteById: (id) => `/api/tickets/delete-ticket/${id}`,
  ticketsGetTicketClientById: (id) => `/api/tickets/get-ticket-client/${id}`,
  ticketsMatchClientById: (id) => `/api/tickets/match-client/${id}`,
  ticketsUnmatched: `/api/tickets/unmatched`,
  ticketsUpdateById: (id) => `/api/tickets/update-ticket/${id}`,
  updateAttendance: `/api/update-attendance`,
  updateCompletionPercentage: `/api/update-completion-percentage`,
  updateContactStatus: `/api/update-contact-status`,
  updateContactStatusFacebook: `/api/update-contact-status-facebook`,
  updateDepartmentById: (id) => `/api/update-department/${id}`,
  updateDesignationById: (id) => `/api/update-designation/${id}`,
  updateFeaturePermission: `/api/update-feature-permission`,
  updateNotice: `/api/update-notice`,
  updatePhaseById: (id) => `/api/update-phase/${id}`,
  updatePriorityById: (id) => `/api/update-priority/${id}`,
  updateProductById: (id) => `/api/update-product/${id}`,
  updateProspect: `/api/update-prospect`,
  updateProspectViewPreference: `/api/update-prospect-view-preference`,
  updateProspectStageById: (id) => `/api/update-prospect-stage/${id}`,
  updateProspectStageOrder: `/api/update-prospect-stage-order`,
  updateRoleFeaturePermissions: `/api/update-role-feature-permissions`,
  updateRoleById: (id) => `/api/update-role/${id}`,
  updateShowCompletionPercentage: `/api/update-show-completion-percentage`,
  updateTask: `/api/update-task`,
  updateTaskWorkflowStatus: `/api/update-task-status`,
  updateTaskStatusMaster: (id) => `/api/update-task-status/${id}`,
  updateTaskTypeById: (id) => `/api/update-task-type/${id}`,
  updateUserModePreference: `/api/update-user-mode-preference`,
  updateUserinfo: `/api/update-userinfo`,
  uploadUserImage: `/api/upload-user-image`,
  userFeaturePermissionsById: (id) => `/api/user-feature-permissions/${id}`,
  visitAdd: `/api/visit/add`,
  visitAll: `/api/visit/all`,
  visitAllDatewise: `/api/visit/all/datewise`,
  visitDateEmp: (date, emp) => `/api/visit/date/emp?date=${date}${emp ? `&employee_id=${emp}` : ""}`,
  visitEmployeeById: (id) => `/api/visit/employee/${id}`,
  visitEmployeeScheduleById: (id) => `/api/visit/employee/${id}/schedule`,
  visitStartById: (id) => `/api/visit/start/${id}`,
  visitCompleteById: (id) => `/api/visit/complete/${id}`,
  visitUpdateById: (id) => `/api/visit/update/${id}`,
  visitDeleteById: (id) => `/api/visit/delete/${id}`,
  workReports: `/api/work-reports`,
  workReportsByDate: `/api/work-reports/by-date`,
  workReportsUserById: (id) => `/api/work-reports/user/${id}`,
  zones: `/api/zones`,
};

export default API_URL;
